### ISSUE TITLE
Noindex search template

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/developer-site#58]
The search template - https://developer.yoast.com/search/?q=cats - should include a meta robots tag, with a `noindex, follow` directive.

**Comment by jcomack** [comment]
Submitted a core PR to Docusaurus to tackle this, as trying to do this locally is nearly impossible https://github.com/facebook/docusaurus/pull/3233

**Comment by jcomack** [comment]
Closing this as Docusaurus now ships with this.
